version: 1
builder:
  configs:
  - platform: ios
    scheme: Stores
  - platform: macos-xcodebuild
    scheme: Stores
  - platform: tvos
    scheme: Stores
  - platform: watchos
    scheme: Stores
  - documentation_targets:
      - Stores
      - Blueprints
      - UserDefaultsStore
      - FileSystemStore
      - CoreDataStore
      - KeychainStore
      - TestUtils
